// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estimate_copula
arma::mat estimate_copula(arma::vec& t1, arma::vec& t2, double max_c, Rcpp::List& km1, Rcpp::List& km2, Rcpp::List& kmc, int m, double tau1, double tau2);
RcppExport SEXP _CRFparallel_estimate_copula(SEXP t1SEXP, SEXP t2SEXP, SEXP max_cSEXP, SEXP km1SEXP, SEXP km2SEXP, SEXP kmcSEXP, SEXP mSEXP, SEXP tau1SEXP, SEXP tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type max_c(max_cSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type km1(km1SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type km2(km2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type kmc(kmcSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type tau1(tau1SEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_copula(t1, t2, max_c, km1, km2, kmc, m, tau1, tau2));
    return rcpp_result_gen;
END_RCPP
}
// bernstein_estimator_vec
arma::vec bernstein_estimator_vec(const arma::vec& s1, const arma::vec& s2, int m, double tau1, double tau2, const arma::mat& copula);
RcppExport SEXP _CRFparallel_bernstein_estimator_vec(SEXP s1SEXP, SEXP s2SEXP, SEXP mSEXP, SEXP tau1SEXP, SEXP tau2SEXP, SEXP copulaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type tau1(tau1SEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type copula(copulaSEXP);
    rcpp_result_gen = Rcpp::wrap(bernstein_estimator_vec(s1, s2, m, tau1, tau2, copula));
    return rcpp_result_gen;
END_RCPP
}
// row_kron
arma::mat row_kron(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _CRFparallel_row_kron(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(row_kron(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// band_chol_cpp
arma::mat band_chol_cpp(arma::mat B);
RcppExport SEXP _CRFparallel_band_chol_cpp(SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(band_chol_cpp(B));
    return rcpp_result_gen;
END_RCPP
}
// sdiag_cpp
arma::vec sdiag_cpp(const arma::mat& A, int k);
RcppExport SEXP _CRFparallel_sdiag_cpp(SEXP ASEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(sdiag_cpp(A, k));
    return rcpp_result_gen;
END_RCPP
}
// compute_D1_cpp
arma::mat compute_D1_cpp(const arma::mat& D, const arma::mat& W1, const arma::vec& h, int pord);
RcppExport SEXP _CRFparallel_compute_D1_cpp(SEXP DSEXP, SEXP W1SEXP, SEXP hSEXP, SEXP pordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type pord(pordSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_D1_cpp(D, W1, h, pord));
    return rcpp_result_gen;
END_RCPP
}
// indgreater
IntegerMatrix indgreater(NumericVector x);
RcppExport SEXP _CRFparallel_indgreater(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(indgreater(x));
    return rcpp_result_gen;
END_RCPP
}
// indless
IntegerMatrix indless(NumericVector x);
RcppExport SEXP _CRFparallel_indless(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(indless(x));
    return rcpp_result_gen;
END_RCPP
}
// indequal
IntegerMatrix indequal(NumericVector x);
RcppExport SEXP _CRFparallel_indequal(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(indequal(x));
    return rcpp_result_gen;
END_RCPP
}
// riskset_fast
arma::Mat<int> riskset_fast(arma::vec x, arma::vec y);
RcppExport SEXP _CRFparallel_riskset_fast(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(riskset_fast(x, y));
    return rcpp_result_gen;
END_RCPP
}
// delta
IntegerMatrix delta(NumericVector x, NumericVector y);
RcppExport SEXP _CRFparallel_delta(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(delta(x, y));
    return rcpp_result_gen;
END_RCPP
}
// loglikC
double loglikC(arma::colvec& x, const Rcpp::List& datalist, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _CRFparallel_loglikC(SEXP xSEXP, SEXP datalistSEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(loglikC(x, datalist, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// gradient_fast
arma::vec gradient_fast(arma::colvec& x, const Rcpp::List& datalist, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _CRFparallel_gradient_fast(SEXP xSEXP, SEXP datalistSEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_fast(x, datalist, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// hessian_fast
arma::mat hessian_fast(arma::colvec& x, const Rcpp::List& datalist, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _CRFparallel_hessian_fast(SEXP xSEXP, SEXP datalistSEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(hessian_fast(x, datalist, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// hessian_fast_efficient
arma::mat hessian_fast_efficient(arma::colvec& x, const Rcpp::List& datalist, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _CRFparallel_hessian_fast_efficient(SEXP xSEXP, SEXP datalistSEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(hessian_fast_efficient(x, datalist, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// hessian_fast_batched
arma::mat hessian_fast_batched(arma::colvec& x, const Rcpp::List& datalist, const arma::mat& X1, const arma::mat& X2, int batch_size);
RcppExport SEXP _CRFparallel_hessian_fast_batched(SEXP xSEXP, SEXP datalistSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian_fast_batched(x, datalist, X1, X2, batch_size));
    return rcpp_result_gen;
END_RCPP
}
// hessian_fast_batched_parallel
arma::mat hessian_fast_batched_parallel(arma::colvec& x, const Rcpp::List& datalist, const arma::mat& X1, const arma::mat& X2, int batch_size);
RcppExport SEXP _CRFparallel_hessian_fast_batched_parallel(SEXP xSEXP, SEXP datalistSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian_fast_batched_parallel(x, datalist, X1, X2, batch_size));
    return rcpp_result_gen;
END_RCPP
}
// gradient_poly_fast
arma::vec gradient_poly_fast(arma::colvec& x, const Rcpp::List& datalist, const arma::uvec& keep_idx, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _CRFparallel_gradient_poly_fast(SEXP xSEXP, SEXP datalistSEXP, SEXP keep_idxSEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type keep_idx(keep_idxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_poly_fast(x, datalist, keep_idx, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// hessian_poly_batched_parallel
arma::mat hessian_poly_batched_parallel(arma::colvec& x, const Rcpp::List& datalist, const arma::uvec& keep_idx, const arma::mat& X1, const arma::mat& X2, int batch_size);
RcppExport SEXP _CRFparallel_hessian_poly_batched_parallel(SEXP xSEXP, SEXP datalistSEXP, SEXP keep_idxSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type keep_idx(keep_idxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian_poly_batched_parallel(x, datalist, keep_idx, X1, X2, batch_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CRFparallel_estimate_copula", (DL_FUNC) &_CRFparallel_estimate_copula, 9},
    {"_CRFparallel_bernstein_estimator_vec", (DL_FUNC) &_CRFparallel_bernstein_estimator_vec, 6},
    {"_CRFparallel_row_kron", (DL_FUNC) &_CRFparallel_row_kron, 2},
    {"_CRFparallel_band_chol_cpp", (DL_FUNC) &_CRFparallel_band_chol_cpp, 1},
    {"_CRFparallel_sdiag_cpp", (DL_FUNC) &_CRFparallel_sdiag_cpp, 2},
    {"_CRFparallel_compute_D1_cpp", (DL_FUNC) &_CRFparallel_compute_D1_cpp, 4},
    {"_CRFparallel_indgreater", (DL_FUNC) &_CRFparallel_indgreater, 1},
    {"_CRFparallel_indless", (DL_FUNC) &_CRFparallel_indless, 1},
    {"_CRFparallel_indequal", (DL_FUNC) &_CRFparallel_indequal, 1},
    {"_CRFparallel_riskset_fast", (DL_FUNC) &_CRFparallel_riskset_fast, 2},
    {"_CRFparallel_delta", (DL_FUNC) &_CRFparallel_delta, 2},
    {"_CRFparallel_loglikC", (DL_FUNC) &_CRFparallel_loglikC, 4},
    {"_CRFparallel_gradient_fast", (DL_FUNC) &_CRFparallel_gradient_fast, 4},
    {"_CRFparallel_hessian_fast", (DL_FUNC) &_CRFparallel_hessian_fast, 4},
    {"_CRFparallel_hessian_fast_efficient", (DL_FUNC) &_CRFparallel_hessian_fast_efficient, 4},
    {"_CRFparallel_hessian_fast_batched", (DL_FUNC) &_CRFparallel_hessian_fast_batched, 5},
    {"_CRFparallel_hessian_fast_batched_parallel", (DL_FUNC) &_CRFparallel_hessian_fast_batched_parallel, 5},
    {"_CRFparallel_gradient_poly_fast", (DL_FUNC) &_CRFparallel_gradient_poly_fast, 5},
    {"_CRFparallel_hessian_poly_batched_parallel", (DL_FUNC) &_CRFparallel_hessian_poly_batched_parallel, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CRFparallel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
