# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_kron <- function(X, Y) {
    .Call(`_CRFparallel_row_kron`, X, Y)
}

indgreater <- function(x) {
    .Call(`_CRFparallel_indgreater`, x)
}

indless <- function(x) {
    .Call(`_CRFparallel_indless`, x)
}

indequal <- function(x) {
    .Call(`_CRFparallel_indequal`, x)
}

riskset_fast <- function(x, y) {
    .Call(`_CRFparallel_riskset_fast`, x, y)
}

delta <- function(x, y) {
    .Call(`_CRFparallel_delta`, x, y)
}

loglikC <- function(x, datalist, X1, X2) {
    .Call(`_CRFparallel_loglikC`, x, datalist, X1, X2)
}

gradient_fast <- function(x, datalist, X1, X2) {
    .Call(`_CRFparallel_gradient_fast`, x, datalist, X1, X2)
}

hessian_fast <- function(x, datalist, X1, X2) {
    .Call(`_CRFparallel_hessian_fast`, x, datalist, X1, X2)
}

hessian_fast_efficient <- function(x, datalist, X1, X2) {
    .Call(`_CRFparallel_hessian_fast_efficient`, x, datalist, X1, X2)
}

hessian_fast_batched <- function(x, datalist, X1, X2, batch_size = 1000L) {
    .Call(`_CRFparallel_hessian_fast_batched`, x, datalist, X1, X2, batch_size)
}

hessian_fast_batched_parallel <- function(x, datalist, X1, X2, batch_size = 1000L) {
    .Call(`_CRFparallel_hessian_fast_batched_parallel`, x, datalist, X1, X2, batch_size)
}

gradient_poly_fast <- function(x, datalist, keep_idx, X1, X2) {
    .Call(`_CRFparallel_gradient_poly_fast`, x, datalist, keep_idx, X1, X2)
}

hessian_poly_batched_parallel <- function(x, datalist, keep_idx, X1, X2, batch_size = 1000L) {
    .Call(`_CRFparallel_hessian_poly_batched_parallel`, x, datalist, keep_idx, X1, X2, batch_size)
}

