# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_kron <- function(X, Y) {
    .Call(`_CRFparallel_row_kron`, X, Y)
}

IndGreater <- function(x) {
    .Call(`_CRFparallel_IndGreater`, x)
}

IndLess <- function(x) {
    .Call(`_CRFparallel_IndLess`, x)
}

IndEqual <- function(x) {
    .Call(`_CRFparallel_IndEqual`, x)
}

riskset_fast <- function(x, y) {
    .Call(`_CRFparallel_riskset_fast`, x, y)
}

DeltaC <- function(x, y) {
    .Call(`_CRFparallel_DeltaC`, x, y)
}

logLikC <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6) {
    .Call(`_CRFparallel_logLikC`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6)
}

gradientNew <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, X1, X2, idxN1, idxN2) {
    .Call(`_CRFparallel_gradientNew`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, X1, X2, idxN1, idxN2)
}

gradientPoly <- function(riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4, I5, I6) {
    .Call(`_CRFparallel_gradientPoly`, riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4, I5, I6)
}

hessianNew <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, X1, X2, idxN1, idxN2) {
    .Call(`_CRFparallel_hessianNew`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, X1, X2, idxN1, idxN2)
}

hessian_fast <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, X1, X2, idxN1, idxN2) {
    .Call(`_CRFparallel_hessian_fast`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, X1, X2, idxN1, idxN2)
}

hessianPolyC <- function(riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4) {
    .Call(`_CRFparallel_hessianPolyC`, riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4)
}

